### ISSUE TITLE
Splitting PyDatalab into Runtime and Notebook packages.

### ISSUE THREAD

**Issue by qimingj** [googledatalab/pydatalab#527] opened 2017-09-25 16:53 UTC
In some cases where users want to use Python BQ APIs (or maybe ML APIs) as a pure library (such as running in a service), the notebook related features are not needed, hence it does not make sense to have IPython, Matplotlib, etc as dependencies.

After split, the runtime part should depend on only limited non-UI libraries such as numpy, pandas. The notebook part will depend on runtime, as well as other UI related libraries such as matplotlib, IPython, etc.

**Comment by rajivpb** [comment] 2017-12-19 00:34
Dupe of https://github.com/googledatalab/pydatalab/issues/524

**Closed by rajivpb** 2017-12-19 00:34 UTC
